In [1]:
import lightgbm as lgb
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.utils.multiclass import unique_labels
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from statistics import mean
from pytorch_tabnet.tab_model import TabNetClassifier, TabNetRegressor
from pytorch_tabnet.multitask import TabNetMultiTaskClassifier
from pytorch_tabnet.tab_model import TabNetClassifier
import torch
from statistics import mean
from sklearn.metrics import make_scorer
from sklearn.model_selection import StratifiedKFold, KFold, train_test_split

In [2]:
df = pd.read_csv('../data/JMpreprocessed_dataRedBlueSwapped.csv')

In [3]:
#splitting up data into training/testing
y = df['Winner']
X = df.drop(columns = 'Winner')

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=43)

In [4]:
X.head()

,B_avg_KD,B_avg_opp_KD,B_avg_SIG_STR_pct,B_avg_opp_SIG_STR_pct,B_avg_TD_pct,B_avg_opp_TD_pct,B_avg_SUB_ATT,B_avg_opp_SUB_ATT,B_avg_REV,B_avg_opp_REV,...,B_Stance_Orthodox,B_Stance_Sideways,B_Stance_Southpaw,B_Stance_Switch,R_Stance_Open Stance,R_Stance_Orthodox,R_Stance_Sideways,R_Stance_Southpaw,R_Stance_Switch,VALUE
0,0.316196,0.386883,0.784055,0.538112,0.791148,0.017896,0.032227,0.000015,0.000000,0.0,...,1,0,0,0,0,1,0,0,0,1
1,0.001991,0.289082,0.444719,0.516684,0.141343,0.000017,0.016671,0.023640,0.007814,0.0,...,1,0,0,0,0,0,0,0,1,0
2,0.002097,0.125004,0.418471,0.218668,0.066361,0.083334,0.003906,0.550825,0.031251,0.0,...,0,0,1,0,0,1,0,0,0,1
3,0.015625,0.000000,0.450000,0.428447,0.250000,0.200000,0.148449,0.125000,0.000000,0.0,...,0,0,1,0,0,1,0,0,0,0
4,0.033203,0.015625,0.413535,0.409043,0.243203,0.037305,0.693359,0.000000,0.017578,0.0,...,1,0,0,0,0,0,0,1,0,1

In [15]:
d_train = lgb.Dataset(X_train, label=y_train)
params = {}
params['learning_rate'] = 0.0001
params['boosting_type'] = 'gbdt'
params['objective'] = 'binary'
params['metric'] = 'auc'
params['sub_feature'] = 0.5
params['num_leaves'] = 100
params['min_data'] = 50
params['max_depth'] = 50
clf = lgb.train(params, d_train, 100)

TypeError: train() got an unexpected keyword argument 'nfold'

In [6]:
#Prediction
y_pred=clf.predict(X_test)
#convert into binary values
for i in range(0, len(y_pred)):
    if y_pred[i]>=.5:       # setting threshold to .5
       y_pred[i]=1
    else:  
       y_pred[i]=0

In [7]:
accuracy_score(y_pred,y_test)

0.4486301369863014

In [8]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[131,   0],
       [161,   0]])